name: Deploy to Pantheon

on:
  push:
    branches:
      - main   # Solo corre cuando hay merge/push en main de GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Terminus
        run: |
          curl -L https://pantheon.io/terminus.phar -o terminus
          chmod +x terminus
          sudo mv terminus /usr/local/bin/terminus
          terminus --version   # Verificamos que quedó instalado

      - name: Authenticate Terminus
        run: terminus auth:login --machine-token=$PANTHEON_MACHINE_TOKEN
        env:
          PANTHEON_MACHINE_TOKEN: ${{ secrets.PANTHEON_MACHINE_TOKEN }}

      - name: Push code to Pantheon
        run: |
          terminus connection:set example-abcde.dev git
          git remote remove pantheon || true
          git remote add pantheon $(terminus connection:info example-abcde.dev --field=git_url)
          git push pantheon main:master --force
